import logging

from fpdf import FPDF
from challanai.core.config import DEFAULT_CONFIG

logger = logging.getLogger(__name__)

# Column widths for the PDF table (must sum to ~190mm for A4 page width)
PDF_COLUMN_WIDTHS = [22, 28, 22, 18, 20, 20, 16, 22]


class InvoicePDF(FPDF):
    """PDF invoice renderer with automatic header and footer."""

    def __init__(self, config: dict):
        super().__init__()
        self.config = config
        self.set_auto_page_break(auto=True, margin=15)

    def header(self) -> None:
        """Render the company header at the top of each page."""
        company = self.config.get("company", DEFAULT_CONFIG["company"])

        self.set_font("Helvetica", "B", 18)
        self.cell(0, 10, company["name"], align="C", new_x="LMARGIN", new_y="NEXT")

        self.set_font("Helvetica", "", 9)
        self.cell(0, 5, company["subtitle"], align="C", new_x="LMARGIN", new_y="NEXT")
        self.cell(0, 5, company["address"], align="C", new_x="LMARGIN", new_y="NEXT")
        self.cell(
            0,
            5,
            f"Contact: {company['contact']}",
            align="C",
            new_x="LMARGIN",
            new_y="NEXT",
        )
        self.cell(
            0,
            5,
            f"GSTN: {company['gstn']}  |  PAN: {company['pan']}",
            align="C",
            new_x="LMARGIN",
            new_y="NEXT",
        )

        self.set_font("Helvetica", "B", 11)
        self.cell(
            0, 8, "TAX INVOICE", align="C", new_x="LMARGIN", new_y="NEXT", border="TB"
        )
        self.ln(2)

    def footer(self) -> None:
        """Render the version footer at the bottom of each page."""
        self.set_y(-15)
        self.set_font("Helvetica", "I", 7)
        self.cell(0, 10, "Generated by ChallanAI", align="C")


class InvoicePDFRenderer:
    """Renderer responsible for translating processed data dictionaries into PDF Reports."""

    def __init__(self, data: dict):
        self.data = data
        self.config = data["config"]
        self.pdf = InvoicePDF(self.config)

    def render(self) -> InvoicePDF:
        """Build a PDF representation of the invoice from processed data."""
        self.pdf.add_page()
        self._write_metadata()
        self._write_buyer_details()
        self._write_table()
        self._write_tax_summary()
        self._write_bank_details()
        return self.pdf

    def _write_metadata(self):
        invoice_num = self.data["inv_num"]
        fiscal_year = self.data["fiscal_year"]
        invoice_date = self.data["invoice_date"]

        self.pdf.set_font("Helvetica", "B", 9)
        half_width = 95
        self.pdf.cell(
            half_width, 6, f"Invoice No: {invoice_num}-{fiscal_year}", border=1
        )
        self.pdf.cell(
            half_width,
            6,
            f"Date: {invoice_date.strftime('%d-%m-%Y')}",
            border=1,
            new_x="LMARGIN",
            new_y="NEXT",
        )

    def _write_buyer_details(self):
        buyer = self.config["buyer"]
        self.pdf.set_font("Helvetica", "", 8)
        buyer_block = (
            f"To: {buyer['name']}\n{buyer['address'].strip()}\nGSTIN: {buyer['gstn']}"
        )
        self.pdf.multi_cell(0, 4, buyer_block, border=1)
        self.pdf.ln(3)

    def _write_table(self):
        headers = [
            "Date",
            "Material",
            "Site",
            "Challan",
            "Qty",
            "Rate",
            "Per",
            "Amount",
        ]
        self.pdf.set_font("Helvetica", "B", 8)
        for i, text in enumerate(headers):
            self.pdf.cell(PDF_COLUMN_WIDTHS[i], 6, text, border=1, align="C")
        self.pdf.ln()

        self.pdf.set_font("Helvetica", "", 7.5)
        for site_info in self.data["sites_data"]:
            date_text = site_info["date_range_label"].replace("\n", " ")

            for idx, material_name in enumerate(self.data["materials"]):
                material_info = site_info["material_data"].get(material_name, {})
                qty = material_info.get("qty")
                rate = material_info.get("rate")

                amount_text = (
                    f"{round(qty, 2) * float(rate):,.2f}"
                    if (qty is not None and rate is not None)
                    else ""
                )

                row_values = [
                    date_text if idx == 0 else "",
                    material_name,
                    site_info["site_name"],
                    "As Per List" if idx == 0 else "",
                    f"{qty:.2f}" if qty is not None else "",
                    f"{rate:.0f}" if rate is not None else "",
                    self.data["unit"],
                    amount_text,
                ]

                for col_idx, val in enumerate(row_values):
                    self.pdf.cell(
                        PDF_COLUMN_WIDTHS[col_idx], 5, str(val), border="LR", align="C"
                    )
                self.pdf.ln()

        self.pdf.cell(sum(PDF_COLUMN_WIDTHS), 0, "", border="T")
        self.pdf.ln()

    def _write_tax_summary(self):
        label_width = sum(PDF_COLUMN_WIDTHS[:7])
        amount_width = PDF_COLUMN_WIDTHS[7]

        def summary_line(label: str, value: float, bold: bool = False):
            self.pdf.set_font("Helvetica", "B" if bold else "", 8)
            self.pdf.cell(label_width, 6, label, border="LR", align="R")
            self.pdf.cell(amount_width, 6, f"{value:,.2f}", border="LR", align="C")
            self.pdf.ln()

        cgst_pct = int(self.config["gst"]["cgst_rate"] * 100)
        sgst_pct = int(self.config["gst"]["sgst_rate"] * 100)

        summary_line("TOTAL", self.data["total_amount"], bold=True)
        summary_line(f"CGST @ {cgst_pct}%", self.data["cgst_amount"])
        summary_line(f"SGST @ {sgst_pct}%", self.data["sgst_amount"])
        summary_line("ROUND OFF", self.data["round_off"])

        self.pdf.set_font("Helvetica", "B", 9)
        self.pdf.cell(label_width, 7, "GRAND TOTAL", border=1, align="R")
        self.pdf.cell(
            amount_width, 7, f"Rs. {self.data['grand_total']:,}", border=1, align="C"
        )
        self.pdf.ln()

        self.pdf.set_font("Helvetica", "", 7)
        self.pdf.cell(
            0,
            5,
            f"HSN Code: {self.config['gst']['hsn_code']}",
            new_x="LMARGIN",
            new_y="NEXT",
        )
        self.pdf.ln(3)

    def _write_bank_details(self):
        bank = self.config["bank"]
        self.pdf.set_font("Helvetica", "B", 8)
        self.pdf.cell(0, 5, "Bank Details:", new_x="LMARGIN", new_y="NEXT")
        self.pdf.set_font("Helvetica", "", 8)
        self.pdf.cell(
            0,
            5,
            f"{bank['account_name']} | {bank['bank_name']} | A/C: {bank['account_no']} | Branch: {bank['branch']} | IFSC: {bank['ifsc']}",
            new_x="LMARGIN",
            new_y="NEXT",
        )
